version: "3"
services:
  backend:
#    docker compose health check
    depends_on:
      - db
    build: .
    container_name: threesmart-backend
    ports:
      - "7801:7801"
  db:
    image: postgres
    container_name: threesmart-db
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: threesmart
      POSTGRES_DB: threesmart
      POSTGRES_PASSWORD: threesmart
    expose:
      - 5433
    ports:
      - "5433:5432"