server:
  port: 7801
  error:
    include-message: always
spring:
  datasource:
    username: threesmart
    password: threesmart
    #    url: jdbc:postgresql://172.17.0.1:5433/threesmart
    url: jdbc:postgresql://threesmart-db:5432/threesmart
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
  mail:
    host: mail.threesmart.am
    port: 465
    username: noreply@threesmart.am
    password: ThreeSmartNoReplyMardakerner
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          ssl:
            trust: mail.threesmart.am
            protocols: TLSv1.2
            enable: true
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: true