server:
  port: 7801
  error:
    include-message: always
spring:
  datasource:
    username: threesmart
    password: threesmart
    #    url: jdbc:postgresql://172.17.0.1:5433/threesmart
    url: jdbc:postgresql://threesmart-db:5432/threesmart
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
  web:
    resources:
      add-mappings: true