server:
  port: 7801
  error:
    include-message: always
spring:
  datasource:
    username: navio
    password: navio-password
    url: jdbc:postgresql://localhost:5433/navio
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: mail.threesmart.am
    port: 465
    username: noreply@threesmart.am
    password: ThreeSmartNoReplyMardakerner
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          ssl:
            trust: mail.threesmart.am
            protocols: TLSv1.2
            enable: true
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: true