server:
  port: 7801
  error:
    include-message: always
spring:
  datasource:
    username: navio
    password: navio-password
    url: jdbc:postgresql://navio-rds-postgres-instance.cghwgzmy8tl7.eu-north-1.rds.amazonaws.com:5432/navio
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
  mail:
    host: mail.threesmart.am
    port: 465
    username: noreply@threesmart.am
    password: ThreeSmartNoReplyMardakerner
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          ssl:
            trust: mail.threesmart.am
            protocols: TLSv1.2
            enable: true
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: true