server:
  port: 7801
  error:
    include-message: always
spring:
  datasource:
    username: threesmart
    password: threesmart
    #    url: jdbc:postgresql://172.17.0.1:5433/threesmart
    url: jdbc:postgresql://threesmart-db:5432/threesmart
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: rafayel.shahnazaryan@gmail.com
    password: wwtglftmfcgzlhan
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: true